### ISSUE TITLE
添加github workflow

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [looly/hutool#3273]
我看到了pr中的说明跟自测的要求，就想添加一个workflow对pr进行检查怎么样？
就像下面这样
```yml
name: Java CI with Maven

on:
  push:
    branches: [ "v5-dev", "v6-dev" ]
  pull_request:
    branches: [  "v5-dev", "v6-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true -U
      - name: Test with Maven
        run: mvn clean test
```
